In [1]:
## Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
#%matplotlib inline
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
plt.rcParams['figure.figsize'] = [15, 5]
from IPython import display
from ipywidgets import interact, widgets

## Read Data for Cases, Deaths and Recoveries
ConfirmedCases_raw=pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv')
Deaths_raw=pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv')
Recoveries_raw=pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv')


In [2]:
def cleandata(df_raw):
    df_cleaned=df_raw.melt(id_vars=['Province/State','Country/Region','Lat','Long'],value_name='Cases',var_name='Date')
    df_cleaned=df_cleaned.set_index(['Country/Region','Province/State','Date'])
    return df_cleaned 

# Clean all datasets
ConfirmedCases=cleandata(ConfirmedCases_raw)
Deaths=cleandata(Deaths_raw)
Recoveries=cleandata(Recoveries_raw)


In [3]:
def mojafunkcja(r):
  print(3.14*r**2)


In [6]:
mojafunkcja(3)


28.26


In [7]:
a=np.array(["Helo, World"])


In [8]:
a


array(['Helo, World'], dtype='<U11')

In [9]:
a=np.append(a, "a")


In [10]:
a

array(['Helo, World', 'a'], dtype='<U11')

In [11]:
b=np.array([1,3,8,4])


In [12]:
print(np.max(b))

8


In [13]:
np.min(b)


1

In [14]:
np.average(b)

4.0

In [15]:
np.random.rand(3,3)*10

array([[9.16290697, 4.62529243, 2.47812848],
       [1.06632842, 8.12025718, 2.08147737],
       [2.89743183, 0.64567236, 9.1843779 ]])

In [16]:
c=np.array([1,1,1,4])

In [18]:
polska=ConfirmedCases.loc["Poland"]

In [19]:
polska.Cases[-11:-4]

Province/State  Date   
NaN             3/4/20      1
                3/5/20      1
                3/6/20      5
                3/7/20      5
                3/8/20     11
                3/9/20     16
                3/10/20    22
Name: Cases, dtype: int64

In [21]:
polska


Lat     Long  Cases
Province/State Date                            
NaN            1/22/20  51.9194  19.1451      0
               1/23/20  51.9194  19.1451      0
               1/24/20  51.9194  19.1451      0
               1/25/20  51.9194  19.1451      0
               1/26/20  51.9194  19.1451      0
               1/27/20  51.9194  19.1451      0
               1/28/20  51.9194  19.1451      0
               1/29/20  51.9194  19.1451      0
               1/30/20  51.9194  19.1451      0
               1/31/20  51.9194  19.1451      0
               2/1/20   51.9194  19.1451      0
               2/2/20   51.9194  19.1451      0
               2/3/20   51.9194  19.1451      0
               2/4/20   51.9194  19.1451      0
               2/5/20   51.9194  19.1451      0
               2/6/20   51.9194  19.1451      0
               2/7/20   51.9194  19.1451      0
               2/8/20   51.9194  19.1451      0
               2/9/20   51.9194  19.1451      0
               2/10/20  51.9194  19.1451      0
               2/11/20  51.9194  19.1451      0
               2/12/20  51.9194  19.1451      0
               2/13/20  51.9194  19.1451      0
               2/14/20  51.9194  19.1451      0
               2/15/20  51.9194  19.1451      0
               2/16/20  51.9194  19.1451      0
               2/17/20  51.9194  19.1451      0
               2/18/20  51.9194  19.1451      0
               2/19/20  51.9194  19.1451      0
               2/20/20  51.9194  19.1451      0
               2/21/20  51.9194  19.1451      0
               2/22/20  51.9194  19.1451      0
               2/23/20  51.9194  19.1451      0
               2/24/20  51.9194  19.1451      0
               2/25/20  51.9194  19.1451      0
               2/26/20  51.9194  19.1451      0
               2/27/20  51.9194  19.1451      0
               2/28/20  51.9194  19.1451      0
               2/29/20  51.9194  19.1451      0
               3/1/20   51.9194  19.1451      0
               3/2/20   51.9194  19.1451      0
               3/3/20   51.9194  19.1451      0
               3/4/20   51.9194  19.1451      1
               3/5/20   51.9194  19.1451      1
               3/6/20   51.9194  19.1451      5
               3/7/20   51.9194  19.1451      5
               3/8/20   51.9194  19.1451     11
               3/9/20   51.9194  19.1451     16
               3/10/20  51.9194  19.1451     22
               3/11/20  51.9194  19.1451     31
               3/12/20  51.9194  19.1451     49
               3/13/20  51.9194  19.1451     68
               3/14/20  51.9194  19.1451    103

In [22]:
dane=np.random.rand(10)*10


In [23]:
posortowane=np.sort(dane)
posortowane[-3:]

array([6.73707414, 6.84169057, 7.01798288])

In [24]:
dane.sort()
print(dane)

[1.88778657 2.43655486 2.58198488 2.72417857 3.46065686 3.5925069
 4.62473541 6.73707414 6.84169057 7.01798288]


In [29]:
a = np.floor(10*np.random.random((2,2)))


In [30]:
a

array([[9., 0.],
       [0., 0.]])

In [25]:
b = np.floor(10*np.random.random((2,2)))


In [26]:
b

array([[9., 0.],
       [6., 7.]])

In [27]:
np.vstack((a,b))

array([['Helo, World', 'a'],
       ['9.0', '0.0'],
       ['6.0', '7.0']], dtype='<U32')

In [31]:
np.hstack((a,b))

array([[9., 0., 9., 0.],
       [0., 0., 6., 7.]])

In [32]:
pd.Series([1,2,5,7])

0    1
1    2
2    5
3    7
dtype: int64

In [33]:
np.array([1,2,5,7])

array([1, 2, 5, 7])

In [34]:
daty = pd.date_range('20200101', periods=10)

In [35]:
daty

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')

In [36]:
df = pd.DataFrame({'komputery': [1,2],
                    'zeszyty': [1,3],
                    'wirusy':[3,5]})

In [37]:
df

komputery  zeszyty  wirusy
0          1        1       3
1          2        3       5

In [38]:
df.columns

Index(['komputery', 'zeszyty', 'wirusy'], dtype='object')

In [39]:
df.to_numpy()

array([[1, 1, 3],
       [2, 3, 5]], dtype=int64)

In [41]:
df.T

0  1
komputery  1  2
zeszyty    1  3
wirusy     3  5

In [42]:
df = pd.DataFrame({'komputery': [1,2,3,4,5,6,2],
                    'zeszyty':  [1,1,1,2,1,2,2],
                    'wirusy':   [8,5,2,4,5,1,2]})

In [43]:
df

komputery  zeszyty  wirusy
0          1        1       8
1          2        1       5
2          3        1       2
3          4        2       4
4          5        1       5
5          6        2       1
6          2        2       2

In [44]:
df.sort_values(by=[0], ascending=True, axis=1)

komputery  zeszyty  wirusy
0          1        1       8
1          2        1       5
2          3        1       2
3          4        2       4
4          5        1       5
5          6        2       1
6          2        2       2